[package]
name = "xq"
version = "0.1.0"
authors = ["Vinnie Magro <v@vinn.ie>"]
edition = "2018"

[lib]
name = "xq"
path = "src/lib.rs"

[dependencies]
graphql-parser = "0.2.3"
Inflector = "0.11.4"
roxmltree = "0.9.0"
serde_json = "1.0.47"