[package]
name = "xq"
version = "0.1.0"
authors = ["Vinnie Magro <v@vinn.ie>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphql-parser = "0.2.3"
roxmltree = "0.9.0"
serde_json = "1.0.47"